### ISSUE TITLE
bower package not getting "installed"

### ISSUE THREAD

**Issue by philippfrenzel** [francoispluchino/composer-asset-plugin#91]
Hi, 

I try to install the bower package "fullcalendar" which works fine by using the commandline, but in combination with yii2 and your extension, it only creates an empty folder without any files inside?

Do you have an idea why this could happen? no case sensitive reasons...

Thanks Phil

**Comment by francoispluchino** [comment]
Do you used the last versions of Composer and plugin (`dev`)?

**Comment by philippfrenzel** [comment]
yes

**Comment by francoispluchino** [comment]
Can you give me your `composer.json` file? Because this bug is fixed by the issue #58.

**Comment by philippfrenzel** [comment]
ok, one sec
{
	"name": "philippfrenzel/yii2fullcalendar",
	"description": "Yii2 fullcalendar Widgets",
	"keywords": ["yii2", "fullcalendar"],
	"homepage": "http://www.frenzel.net/",
	"type": "yii2-extension",
	"license": "MIT License",
	"authors": [
		{
			"name": "Philipp Frenzel",
			"email": "philipp@frenzel.net",
			"homepage": "http://www.frenzel.net/",
			"role": "Author Version Yii2"
		}
	],
	"support": {
		"source": "https://github.com/philippfrenzel/yii2fullcalendar"
	},
	"minimum-stability": "stable",
	"require": {
		"yiisoft/yii2" : "*",
		"yiisoft/yii2-jui": "*",
		"bower-asset/moment" : "*",
		"bower-asset/fullcalendar" : "2.2.*@stable"
	},
	"autoload": {
		"psr-4": { "yii2fullcalendar\\": "" }
	}
}

**Comment by francoispluchino** [comment]
I just tested, and everything is OK.

Update your Composer:
```
$ composer self-update
```
and the plugin:
```
$ composer global update
```

And it should be good.

**Comment by philippfrenzel** [comment]
sorry still not working... thanks for support -> did all you said:

![screenshot 2015-01-20 18 03 47](https://cloud.githubusercontent.com/assets/2319890/5821750/bce8533e-a0ce-11e4-8735-f9039bdfd5d3.png)

**Comment by philippfrenzel** [comment]
the funny thing is, that moment.js is working fine as it comes from the same "reference" file?...

**Comment by francoispluchino** [comment]
Try with remove your vendor directory and relaunch `composer install`.

**Comment by philippfrenzel** [comment]
Works After a complete delete!;) thanks!
